In [2]:
import pandas as pd
import numpy as np


In [3]:
df=pd.read_csv(r"C:\Users\HP\seaborn-data\titanic.csv")

In [4]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [5]:
df.shape

(891, 15)

In [6]:
df.tail()

survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0  30.00        S   First   
888         0       3  female   NaN      1      2  23.45        S   Third   
889         1       1    male  26.0      0      0  30.00        C   First   
890         0       3    male  32.0      0      0   7.75        Q   Third   

       who  adult_male deck  embark_town alive  alone  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True

In [7]:
df.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   survived     891 non-null    int64  
 1   pclass       891 non-null    int64  
 2   sex          891 non-null    object 
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64  
 5   parch        891 non-null    int64  
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object 
 8   class        891 non-null    object 
 9   who          891 non-null    object 
 10  adult_male   891 non-null    bool   
 11  deck         203 non-null    object 
 12  embark_town  889 non-null    object 
 13  alive        891 non-null    object 
 14  alone        891 non-null    bool   
dtypes: bool(2), float64(2), int64(4), object(7)
memory usage: 92.4+ KB


In [9]:
#find total null values in data
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

# Handling null values

In [10]:
df.age=df.age.fillna(df.age.median())

In [11]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [12]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [13]:
df.loc[2:8]

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   
5         0       3    male  28.0      0      0   8.4583        Q  Third   
6         0       1    male  54.0      0      0  51.8625        S  First   
7         0       3    male   2.0      3      1  21.0750        S  Third   
8         1       3  female  27.0      0      2  11.1333        S  Third   

     who  adult_male deck  embark_town alive  alone  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
6    man        True    E  Southampton    no   True  
7  child       False  NaN  Southampton    no  False  
8  woman       False  NaN  Southampton   yes  False

In [14]:
df.loc[df.age>30]

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
1           1       1  female  38.0      1      0  71.2833        C  First   
3           1       1  female  35.0      1      0  53.1000        S  First   
4           0       3    male  35.0      0      0   8.0500        S  Third   
6           0       1    male  54.0      0      0  51.8625        S  First   
11          1       1  female  58.0      0      0  26.5500        S  First   
..        ...     ...     ...   ...    ...    ...      ...      ...    ...   
873         0       3    male  47.0      0      0   9.0000        S  Third   
879         1       1  female  56.0      0      1  83.1583        C  First   
881         0       3    male  33.0      0      0   7.8958        S  Third   
885         0       3  female  39.0      0      5  29.1250        Q  Third   
890         0       3    male  32.0      0      0   7.7500        Q  Third   

       who  adult_male deck  embark_town alive  alone  
1    woman       False    C    Cherbourg   yes  False  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
6      man        True    E  Southampton    no   True  
11   woman       False    C  Southampton   yes   True  
..     ...         ...  ...          ...   ...    ...  
873    man        True  NaN  Southampton    no   True  
879  woman       False    C    Cherbourg   yes  False  
881    man        True  NaN  Southampton    no   True  
885  woman       False  NaN   Queenstown    no  False  
890    man        True  NaN   Queenstown    no   True  

[305 rows x 15 columns]

In [15]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [16]:
df.sex.value_counts()

male      577
female    314
Name: sex, dtype: int64

In [17]:
from collections import Counter as count

In [18]:
count(df.adult_male)

Counter({True: 537, False: 354})

# LABEL ENCODING

converting categorical class into numbers

#METHOD 1

In [19]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
print("Before Label ENcoder ",count(df.sex))
df.sex=le.fit_transform(df.sex)     #encode to numerical values
print("After Label ENcoder ",count(df.sex))

Before Label ENcoder  Counter({'male': 577, 'female': 314})
After Label ENcoder  Counter({1: 577, 0: 314})


METHOD 2

In [20]:
print("Before Label ENcoder ",count(df.alive))
df['alive']=df['alive'].replace(['yes','no'],[1,0])    #encode to numerical values
print("After Label ENcoder ",count(df.alive))

Before Label ENcoder  Counter({'no': 549, 'yes': 342})
After Label ENcoder  Counter({0: 549, 1: 342})


In [21]:
print("Before Label ENcoder ",count(df.who))
df['who']=df['who'].replace(['woman','man','child'],[1,2,3])    #encode to numerical values
print("After Label ENcoder ",count(df.who))

Before Label ENcoder  Counter({'man': 537, 'woman': 271, 'child': 83})
After Label ENcoder  Counter({2: 537, 1: 271, 3: 83})


In [22]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
print("Before Label ENcoder ",count(df.alone))
df.alone=le.fit_transform(df.alone)     #encode to numerical values
print("After Label ENcoder ",count(df.alone))

Before Label ENcoder  Counter({True: 537, False: 354})
After Label ENcoder  Counter({1: 537, 0: 354})


In [23]:
df.embark_town.unique()

array(['Southampton', 'Cherbourg', 'Queenstown', nan], dtype=object)

In [24]:
print("Before Label ENcoder ",count(df.embark_town))
df['embark_town']=df['embark_town'].replace(['Southampton','Cherbourg','Queenstown','nan'],[1,2,3,4])    #encode to numerical values
print("After Label ENcoder ",count(df.embark_town))

Before Label ENcoder  Counter({'Southampton': 644, 'Cherbourg': 168, 'Queenstown': 77, nan: 2})
After Label ENcoder  Counter({1.0: 644, 2.0: 168, 3.0: 77, nan: 1, nan: 1})


In [25]:
df.adult_male.unique()

array([ True, False])

In [26]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
print("Before Label ENcoder ",count(df.adult_male))
df.adult_male=le.fit_transform(df.adult_male)     #encode to numerical values
print("After Label ENcoder ",count(df.adult_male))

Before Label ENcoder  Counter({True: 537, False: 354})
After Label ENcoder  Counter({1: 537, 0: 354})


In [27]:
df.deck.unique()

array([nan, 'C', 'E', 'G', 'D', 'A', 'B', 'F'], dtype=object)

In [28]:
print("Before Label ENcoder ",count(df.deck))
df['deck']=df['deck'].replace(['nan','C', 'E', 'G', 'D', 'A', 'B', 'F'],[0,3,5,7,4,1,2,6])    #encode to numerical values
print("After Label ENcoder ",count(df.deck))

Before Label ENcoder  Counter({nan: 688, 'C': 59, 'B': 47, 'D': 33, 'E': 32, 'A': 15, 'F': 13, 'G': 4})
After Label ENcoder  Counter({3.0: 59, 2.0: 47, 4.0: 33, 5.0: 32, 1.0: 15, 6.0: 13, 7.0: 4, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan:

In [29]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [30]:
df.deck=df.deck.fillna(df.deck.median())

In [31]:
df.embarked.unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [32]:
df.embarked.unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [33]:
print("Before Label ENcoder ",count(df.embarked))
df['embarked']=df['embarked'].replace(['nan','S', 'C', 'Q'],[0,1,2,3])    #encode to numerical values
print("After Label ENcoder ",count(df.embarked))

Before Label ENcoder  Counter({'S': 644, 'C': 168, 'Q': 77, nan: 2})
After Label ENcoder  Counter({1.0: 644, 2.0: 168, 3.0: 77, nan: 1, nan: 1})


In [34]:
df.shape

(891, 15)

In [35]:
df

survived  pclass  sex   age  sibsp  parch     fare  embarked   class  \
0           0       3    1  22.0      1      0   7.2500       1.0   Third   
1           1       1    0  38.0      1      0  71.2833       2.0   First   
2           1       3    0  26.0      0      0   7.9250       1.0   Third   
3           1       1    0  35.0      1      0  53.1000       1.0   First   
4           0       3    1  35.0      0      0   8.0500       1.0   Third   
..        ...     ...  ...   ...    ...    ...      ...       ...     ...   
886         0       2    1  27.0      0      0  13.0000       1.0  Second   
887         1       1    0  19.0      0      0  30.0000       1.0   First   
888         0       3    0  28.0      1      2  23.4500       1.0   Third   
889         1       1    1  26.0      0      0  30.0000       2.0   First   
890         0       3    1  32.0      0      0   7.7500       3.0   Third   

     who  adult_male  deck  embark_town  alive  alone  
0      2           1   3.0          1.0      0      0  
1      1           0   3.0          2.0      1      0  
2      1           0   3.0          1.0      1      1  
3      1           0   3.0          1.0      1      0  
4      2           1   3.0          1.0      0      1  
..   ...         ...   ...          ...    ...    ...  
886    2           1   3.0          1.0      0      1  
887    1           0   2.0          1.0      1      1  
888    1           0   3.0          1.0      0      0  
889    2           1   3.0          2.0      1      1  
890    2           1   3.0          3.0      0      1  

[891 rows x 15 columns]

In [36]:
del df['class']

In [37]:
df

survived  pclass  sex   age  sibsp  parch     fare  embarked  who  \
0           0       3    1  22.0      1      0   7.2500       1.0    2   
1           1       1    0  38.0      1      0  71.2833       2.0    1   
2           1       3    0  26.0      0      0   7.9250       1.0    1   
3           1       1    0  35.0      1      0  53.1000       1.0    1   
4           0       3    1  35.0      0      0   8.0500       1.0    2   
..        ...     ...  ...   ...    ...    ...      ...       ...  ...   
886         0       2    1  27.0      0      0  13.0000       1.0    2   
887         1       1    0  19.0      0      0  30.0000       1.0    1   
888         0       3    0  28.0      1      2  23.4500       1.0    1   
889         1       1    1  26.0      0      0  30.0000       2.0    2   
890         0       3    1  32.0      0      0   7.7500       3.0    2   

     adult_male  deck  embark_town  alive  alone  
0             1   3.0          1.0      0      0  
1             0   3.0          2.0      1      0  
2             0   3.0          1.0      1      1  
3             0   3.0          1.0      1      0  
4             1   3.0          1.0      0      1  
..          ...   ...          ...    ...    ...  
886           1   3.0          1.0      0      1  
887           0   2.0          1.0      1      1  
888           0   3.0          1.0      0      0  
889           1   3.0          2.0      1      1  
890           1   3.0          3.0      0      1  

[891 rows x 14 columns]

# One Hot Encoding

In [38]:
from sklearn.compose import ColumnTransformer  #It is used for performing both OHE and LE in single step
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer([('on',OneHotEncoder(),[0])],remainder='passthrough')
df=ct.fit_transform(df)

In [39]:
df.shape

(891, 15)

In [40]:
df

array([[1., 0., 3., ..., 1., 0., 0.],
       [0., 1., 1., ..., 2., 1., 0.],
       [0., 1., 3., ..., 1., 1., 1.],
       ...,
       [1., 0., 3., ..., 1., 0., 0.],
       [0., 1., 1., ..., 2., 1., 1.],
       [1., 0., 3., ..., 3., 0., 1.]])

# STANDARD SCALAR  / FEATURE SCALING

In [41]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
df=sc.fit_transform(df)    # fit_transform :Learns from data and applies that learning and can be stored in dataframe.
                           #while fit only learns and doesnot applies

In [42]:
df

array([[ 0.78927234, -0.78927234,  0.82737724, ..., -0.56968402,
        -0.78927234, -1.2316449 ],
       [-1.2669898 ,  1.2669898 , -1.56610693, ...,  1.00313924,
         1.2669898 , -1.2316449 ],
       [-1.2669898 ,  1.2669898 ,  0.82737724, ..., -0.56968402,
         1.2669898 ,  0.81192233],
       ...,
       [ 0.78927234, -0.78927234,  0.82737724, ..., -0.56968402,
        -0.78927234, -1.2316449 ],
       [-1.2669898 ,  1.2669898 , -1.56610693, ...,  1.00313924,
         1.2669898 ,  0.81192233],
       [ 0.78927234, -0.78927234,  0.82737724, ...,  2.5759625 ,
        -0.78927234,  0.81192233]])

In [43]:
df

array([[ 0.78927234, -0.78927234,  0.82737724, ..., -0.56968402,
        -0.78927234, -1.2316449 ],
       [-1.2669898 ,  1.2669898 , -1.56610693, ...,  1.00313924,
         1.2669898 , -1.2316449 ],
       [-1.2669898 ,  1.2669898 ,  0.82737724, ..., -0.56968402,
         1.2669898 ,  0.81192233],
       ...,
       [ 0.78927234, -0.78927234,  0.82737724, ..., -0.56968402,
        -0.78927234, -1.2316449 ],
       [-1.2669898 ,  1.2669898 , -1.56610693, ...,  1.00313924,
         1.2669898 ,  0.81192233],
       [ 0.78927234, -0.78927234,  0.82737724, ...,  2.5759625 ,
        -0.78927234,  0.81192233]])

In [44]:
df.shape

(891, 15)

In [45]:
df

array([[ 0.78927234, -0.78927234,  0.82737724, ..., -0.56968402,
        -0.78927234, -1.2316449 ],
       [-1.2669898 ,  1.2669898 , -1.56610693, ...,  1.00313924,
         1.2669898 , -1.2316449 ],
       [-1.2669898 ,  1.2669898 ,  0.82737724, ..., -0.56968402,
         1.2669898 ,  0.81192233],
       ...,
       [ 0.78927234, -0.78927234,  0.82737724, ..., -0.56968402,
        -0.78927234, -1.2316449 ],
       [-1.2669898 ,  1.2669898 , -1.56610693, ...,  1.00313924,
         1.2669898 ,  0.81192233],
       [ 0.78927234, -0.78927234,  0.82737724, ...,  2.5759625 ,
        -0.78927234,  0.81192233]])

# Train Test Split

In [46]:
#independent variable
x=pd.DataFrame(df[:,0:15],columns=['Southampton', 'Cherbourg', 'Queenstown','pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'who', 'adult_male', 'deck', 
       'alive', 'alone'])
x


Southampton  Cherbourg  Queenstown    pclass       sex       age  \
0       0.789272  -0.789272    0.827377  0.737695 -0.565736  0.432793   
1      -1.266990   1.266990   -1.566107 -1.355574  0.663861  0.432793   
2      -1.266990   1.266990    0.827377 -1.355574 -0.258337 -0.474545   
3      -1.266990   1.266990   -1.566107 -1.355574  0.433312  0.432793   
4       0.789272  -0.789272    0.827377  0.737695  0.433312 -0.474545   
..           ...        ...         ...       ...       ...       ...   
886     0.789272  -0.789272   -0.369365  0.737695 -0.181487 -0.474545   
887    -1.266990   1.266990   -1.566107 -1.355574 -0.796286 -0.474545   
888     0.789272  -0.789272    0.827377 -1.355574 -0.104637  0.432793   
889    -1.266990   1.266990   -1.566107  0.737695 -0.258337 -0.474545   
890     0.789272  -0.789272    0.827377  0.737695  0.202762 -0.474545   

        sibsp     parch      fare  embarked       who  adult_male      deck  \
0   -0.473674 -0.502445 -0.569684  0.355242  0.811922   -0.119419 -0.569684   
1   -0.473674  0.786845  1.003139 -1.328379 -1.231645   -0.119419  1.003139   
2   -0.473674 -0.488854 -0.569684 -1.328379 -1.231645   -0.119419 -0.569684   
3   -0.473674  0.420730 -0.569684 -1.328379 -1.231645   -0.119419 -0.569684   
4   -0.473674 -0.486337 -0.569684  0.355242  0.811922   -0.119419 -0.569684   
..        ...       ...       ...       ...       ...         ...       ...   
886 -0.473674 -0.386671 -0.569684  0.355242  0.811922   -0.119419 -0.569684   
887 -0.473674 -0.044381 -0.569684 -1.328379 -1.231645   -1.538119 -0.569684   
888  2.008933 -0.176263 -0.569684 -1.328379 -1.231645   -0.119419 -0.569684   
889 -0.473674 -0.044381  1.003139  0.355242  0.811922   -0.119419  1.003139   
890 -0.473674 -0.492378  2.575963  0.355242  0.811922   -0.119419  2.575963   

        alive     alone  
0   -0.789272 -1.231645  
1    1.266990 -1.231645  
2    1.266990  0.811922  
3    1.266990 -1.231645  
4   -0.789272  0.811922  
..        ...       ...  
886 -0.789272  0.811922  
887  1.266990  0.811922  
888 -0.789272 -1.231645  
889  1.266990  0.811922  
890 -0.789272  0.811922  

[891 rows x 15 columns]

In [55]:
#dependent variable
y=pd.DataFrame(df[:,14:],columns=['survived'])

In [56]:
y

survived
0   -1.231645
1   -1.231645
2    0.811922
3   -1.231645
4    0.811922
..        ...
886  0.811922
887  0.811922
888 -1.231645
889  0.811922
890  0.811922

[891 rows x 1 columns]

In [ ]:
#splitting dataset into train and test  dataset

In [57]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [61]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(712, 15)
(179, 15)
(712, 1)
(179, 1)
